@startuml jra-van-data

hide circle
skinparam linetype ortho

entity "特別登録馬" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    競走名本題
}

entity "特別登録馬_連番" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    連番 <<PK>>
    --
    血統登録番号
    馬名
}

entity "レース詳細" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    競走名本題
}

entity "馬毎レース情報" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    枠番
    馬番 <<PK>>
    血統登録番号 <<PK>>
    --
    馬名
    騎手コード <<FK>>
    変更前騎手コード <<FK>>
    入線順位
    1コーナーでの順位
    2コーナーでの順位
    3コーナーでの順位
    4コーナーでの順位
    後4ハロンタイム
    後3ハロンタイム
}

entity "払戻" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
}

entity "競走馬マスタ" {
    血統登録番号 <<PK>>
    --
    馬名
    繁殖登録番号_父 <<FK>>
    繁殖登録番号_母 <<FK>>
    調教師コード
    生産者コード
    馬主コード
}

entity "騎手マスタ" {
    騎手コード <<PK>>
    --
    騎手名
}

entity "調教師マスタ" {
    調教師コード <<PK>>
    --
    調教師名
}

entity "生産者マスタ" {
    生産者コード <<PK>>
    --
    生産者名(法人格有)
}

entity "馬主マスタ" {
    馬主コード <<PK>>
    --
    馬主名(法人格有)
}

entity "繁殖馬マスタ" {
    繁殖登録番号 <<PK>>
    --
    血統登録番号 <<FK>>
    馬名
    父馬繁殖登録番号 <<FK>>
    母馬繁殖登録番号 <<FK>>
}

entity "産駒マスタ" {
    血統登録番号 <<PK>>
    ---
    生年月日
}

entity "レコードマスタ" {
    レコード識別区分 <<PK>>
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    特別競走番号 <<PK>>
    競走名本題
    グレードコード
    競走種別コード <<PK>>
    距離 <<PK>>
    トラックコード <<PK>>
    ---
    レコードタイム
    天候コード
    芝馬場状態コード
    ダート馬場状態コード
    レコード保持1_血統登録番号
    レコード保持1_調教師コード
    レコード保持1_騎手コード
    レコード保持1_負担重量
}

entity "坂路調教" {
    トレセン区分 <<PK>>
    調教年月日 <<PK>>
    調教時刻 <<PK>>
    血統登録番号 <<PK>>
    --
    ラップタイム(800M～600M)
    ラップタイム(600M～400M)
    ラップタイム(400M～200M)
    ラップタイム(200M～0M)
}

entity "競走馬市場取引価格" {
    血統登録番号 <<PK>>
    --
    父馬 繁殖登録番号
    母馬 繁殖登録番号
    生年
    主催者・市場コード <<PK>>
    主催者名称
    市場の名称
    市場の開催期間(開始日) <<PK>>
    市場の開催期間(終了日)
    取引時の競走馬の年齢
    取引価格
}

entity "開催スケジュール" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    曜日コード
}

entity "コース情報" {
    競馬場コード <<PK>>
    距離 <<PK>>
    トラックコード <<PK>>
    コース改修年月日 <<PK>>
    --
    コース説明
}

entity "ウッドチップ調教" {
    トレセン区分 <<PK>>
    調教年月日 <<PK>>
    調教時刻 <<PK>>
    血統登録番号 <<PK>>
    ---
    コース
    ラップタイム(2000M～1800M)
    ラップタイム(1800M～1600M)
    ラップタイム(1600M～1400M)
    ラップタイム(1400M～1200M)
    ラップタイム(1200M～1000M)
    ラップタイム(1000M～800M)
    ラップタイム(800M～600M)
    ラップタイム(600M～400M)
    ラップタイム(400M～200M)
    ラップタイム(200M～0M)
}

entity "馬体重" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    発表月日時分
    馬番 <<PK>>
    ---
    馬名
    馬体重
    増減差
}

entity "天候馬場状態" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    発表月日時分 <<PK>>
    変更識別 <<PK>>
    --
    現在_天候状態
    現在_馬場状態・芝
    現在_馬場状態・ダート
}

entity "出走取消・競走除外" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    発表月日時分
    馬番 <<PK>>
    --
    馬名
    事由区分
}

entity "騎手変更" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    発表月日時分 <<PK>>
    馬番 <<PK>>
    --
    馬名
    変更後_騎手コード
    変更前_騎手コード
}

entity "発走時刻変更" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    変更後_発走時刻
    変更前_発走時刻
}

entity "コース変更" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    変更後_距離
    変更後_トラックコード
    変更前_距離
    変更前_トラックコード
    事由区分
}


"特別登録馬" ||--|{ "特別登録馬_連番"
"特別登録馬" ||--|| "レース詳細"
"特別登録馬_連番" ||--|{ "馬毎レース情報"
"特別登録馬" ||--|| "払戻"
"特別登録馬_連番" }|--||"競走馬マスタ"
"馬毎レース情報" }|--||"競走馬マスタ"
"馬毎レース情報" }|--|{ "騎手マスタ"
"調教師マスタ" }|--|{ "特別登録馬_連番"
"調教師マスタ" }|--|{ "馬毎レース情報"
"調教師マスタ" }|--|{ "競走馬マスタ"
"調教師マスタ" }|--|{ "騎手マスタ"
"生産者マスタ" ||--|{ "競走馬マスタ"
"馬主マスタ" ||--|{ "競走馬マスタ"
"馬主マスタ" ||--|{ "馬毎レース情報"
"繁殖馬マスタ" }|--|{ "競走馬マスタ"
"繁殖馬マスタ" }|--|{ "繁殖馬マスタ"
"産駒マスタ" ||--|| "競走馬マスタ"
"産駒マスタ" }|--|| "生産者マスタ"
"産駒マスタ" ||--|{ "繁殖馬マスタ"
"レコードマスタ" }|--|{ "競走馬マスタ"
"坂路調教" }|--|{ "競走馬マスタ"
"競走馬市場取引価格" }|--|{ "競走馬マスタ"
"特別登録馬" }|--|| "コース情報"
"ウッドチップ調教" }|--|{ "競走馬マスタ"
"特別登録馬_連番" ||--|| "馬体重"
"開催スケジュール" ||--|{ "特別登録馬"
"開催スケジュール" ||--|{ "天候馬場状態"
"特別登録馬_連番" ||--o "出走取消・競走除外"
"特別登録馬_連番" ||--o{ "騎手変更"
"特別登録馬_連番" ||--o "発走時刻変更"
"特別登録馬_連番" ||--o "コース変更"


@enduml
