@startuml jra-van-data

hide circle
skinparam linetype ortho

entity "特別登録馬" {
    レコード種別ID
    データ区分
    データ作成年月日
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    曜日コード
    特別競走番号
    競走名本題
    競走名副題
    競走名カッコ内
    競走名本題欧字
    競走名副題欧字
    競走名カッコ内欧字
    競走名略称10文字
    競走名略称6文字
    競走名略称3文字
    競走名区分
    重賞回次[第N回]
    グレードコード
    競走種別コード
    競走記号コード
    重量種別コード
    競走条件コード 2歳条件
    競走条件コード 3歳条件
    競走条件コード 4歳条件
    競走条件コード 5歳以上条件
    競走条件コード 最若年条件
    距離
    トラックコード
    コース区分
    ハンデ発表日
    登録頭数
}

entity "特別登録馬_連番" {
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    連番 <<PK>>
    --
    血統登録番号
    --
    馬名
    馬記号コード
    性別コード
    調教師東西所属コード
    調教師コード
    調教師名略称
    負担重量
    交流区分
}

entity "レース詳細" {
    レコード種別ID
    データ区分
    データ作成年月日
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    曜日コード
    特別競走番号
    競走名本題
    競走名副題
    競走名カッコ内
    競走名本題欧字
    競走名副題欧字
    競走名カッコ内欧字
    競走名略称10文字
    競走名略称6文字
    競走名略称3文字
    競走名区分
    重賞回次[第N回]
    グレードコード
    変更前グレードコード
    競走種別コード
    競走記号コード
    重量種別コード
    競走条件コード 2歳条件
    競走条件コード 3歳条件
    競走条件コード 4歳条件
    競走条件コード 5歳以上条件
    競走条件コード 最若年条件
    競走条件名称
    距離
    変更前距離
    トラックコード
    変更前トラックコード
    コース区分
    変更前コース区分
    本賞金
    変更前本賞金
    付加賞金
    変更前付加賞金
    発走時刻
    変更前発走時刻
    登録頭数
    出走頭数
    入線頭数
    天候コード
    芝馬場状態コード
    ダート馬場状態コード
    ラップタイム
    障害マイルタイム
    前3ハロン
    前4ハロン
    後3ハロン
    後4ハロン
    <コーナー通過順位>
    コーナー
    周回数
    各通過順位
    レコード更新区分
}

entity "馬毎レース情報" {
    レコード種別ID
    データ区分
    データ作成年月日
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    枠番
    馬番 <<PK>>
    血統登録番号 <<PK>>
    --
    馬名
    馬記号コード
    性別コード
    品種コード
    毛色コード
    馬齢
    東西所属コード
    調教師コード
    調教師名略称
    馬主コード
    馬主名(法人格無)
    服色標示
    予備
    負担重量
    変更前負担重量
    ブリンカー使用区分
    予備
    騎手コード <<FK>>
    変更前騎手コード <<FK>>
    騎手名略称
    変更前騎手名略称
    騎手見習コード
    変更前騎手見習コード
    馬体重
    増減符号
    増減差
    異常区分コード
    入線順位
    確定着順
    同着区分
    同着頭数
    走破タイム
    着差コード
    ＋着差コード
    ＋＋着差コード
    1コーナーでの順位
    2コーナーでの順位
    3コーナーでの順位
    4コーナーでの順位
    単勝オッズ
    単勝人気順
    獲得本賞金
    獲得付加賞金
    予備
    予備
    後4ハロンタイム
    後3ハロンタイム
    1着馬相手馬_血統登録番号1
    1着馬相手馬_馬名1
    1着馬相手馬_血統登録番号2
    1着馬相手馬_馬名2
    1着馬相手馬_血統登録番号3
    1着馬相手馬_馬名3
    タイム差
    レコード更新区分
    マイニング区分
    マイニング予想走破タイム
    マイニング予想誤差(信頼度)＋
    マイニング予想誤差(信頼度)－
    マイニング予想順位
    今回レース脚質判定
}

entity "払戻" {
    レコード種別ID
    データ区分
    データ作成年月日
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    --
    登録頭数
    出走頭数
    不成立フラグ  単勝
    不成立フラグ  複勝
    不成立フラグ  枠連
    不成立フラグ  馬連
    不成立フラグ  ワイド
    予備
    不成立フラグ  馬単
    不成立フラグ  3連複
    不成立フラグ  3連単
    特払フラグ  単勝
    特払フラグ  複勝
    特払フラグ  枠連
    特払フラグ  馬連
    特払フラグ  ワイド
    予備
    特払フラグ  馬単
    特払フラグ  3連複
    特払フラグ  3連単
    返還フラグ  単勝
    返還フラグ  複勝
    返還フラグ  枠連
    返還フラグ  馬連
    返還フラグ  ワイド
    予備
    返還フラグ  馬単
    返還フラグ  3連複
    返還フラグ  3連単
    返還馬番情報(馬番01～28)
    返還枠番情報(枠番1～8)
    返還同枠情報(枠番1～8)
    単勝払戻_馬番
    単勝払戻_払戻金
    単勝払戻_人気順
    複勝払戻_馬番
    複勝払戻_払戻金
    複勝払戻_人気順
    枠連払戻_組番
    枠連払戻_払戻金
    枠連払戻_人気順
    馬連払戻_組番
    馬連払戻_払戻金
    馬連払戻_人気順
    ワイド払戻_組番
    ワイド払戻_払戻金
    ワイド払戻_人気順
    予備1_予備1
    予備1_予備2
    予備1_予備3
    馬単払戻_組番
    馬単払戻_払戻金
    馬単払戻_人気順
    3連複払戻_組番
    3連複払戻_払戻金
    3連複払戻_人気順
    3連単払戻_組番
    3連単払戻_払戻金
    3連単払戻_人気順
}

entity "競走馬マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    血統登録番号 <<PK>>
    --
    競走馬抹消区分
    競走馬登録年月日
    競走馬抹消年月日
    生年月日
    馬名
    馬名半角ｶﾅ
    馬名欧字
    JRA施設在きゅうフラグ
    予備
    馬記号コード
    性別コード
    品種コード
    毛色コード
    繁殖登録番号_父 <<FK>>
    馬名_父
    繁殖登録番号_母 <<FK>>
    馬名_母
    繁殖登録番号_父父 <<FK>>
    馬名_父父
    繁殖登録番号_父母 <<FK>>
    馬名_父母
    繁殖登録番号_母父 <<FK>>
    馬名_母父
    繁殖登録番号_母母 <<FK>>
    馬名_母母
    繁殖登録番号_父父父 <<FK>>
    馬名_父父父
    繁殖登録番号_父父母 <<FK>>
    馬名_父父母
    繁殖登録番号_父母父 <<FK>>
    馬名_父母父
    繁殖登録番号_父母母 <<FK>>
    馬名_父母母
    繁殖登録番号_母父父 <<FK>>
    馬名_母父父
    繁殖登録番号_母父母 <<FK>>
    馬名_母父母
    繁殖登録番号_母母父 <<FK>>
    馬名_母母父
    繁殖登録番号_母母母 <<FK>>
    馬名_母母母
    東西所属コード
    調教師コード
    調教師名略称
    招待地域名
    生産者コード
    生産者名(法人格無)
    産地名
    馬主コード
    馬主名(法人格無)
    平地本賞金累計
    障害本賞金累計
    平地付加賞金累計
    障害付加賞金累計
    平地収得賞金累計
    障害収得賞金累計
    --
    総合着回数
    中央合計着回数
    <馬場別着回数>
    芝直・着回数
    芝右・着回数
    芝左・着回数
    ダ直・着回数
    ダ右・着回数
    ダ左・着回数
    障害・着回数
    <馬場状態別着回数>
    芝良・着回数
    芝稍・着回数
    芝重・着回数
    芝不・着回数
    ダ良・着回数
    ダ稍・着回数
    ダ重・着回数
    ダ不・着回数
    障良・着回数
    障稍・着回数
    障重・着回数
    障不・着回数
    <距離別着回数>
    芝16下・着回数
    芝22下・着回数
    芝22超・着回数
    ダ16下・着回数
    ダ22下・着回数
    ダ22超・着回数
    脚質傾向
    登録レース数
    レコード区切
}

entity "騎手マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    騎手コード <<PK>>
    騎手抹消区分
    騎手免許交付年月日
    騎手免許抹消年月日
    生年月日
    騎手名
    予備
    騎手名半角ｶﾅ
    騎手名略称
    騎手名欧字
    性別区分
    騎乗資格コード
    騎手見習コード
    騎手東西所属コード
    招待地域名
    所属調教師コード
    所属調教師名略称
}

entity "調教師マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    調教師コード <<PK>>
    調教師抹消区分
    調教師免許交付年月日
    調教師免許抹消年月日
    生年月日
    調教師名
    調教師名半角ｶﾅ
    調教師名略称
    調教師名欧字
    性別区分
    調教師東西所属コード
    招待地域名
}

entity "生産者マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    生産者コード <<PK>>
    生産者名(法人格有)
    生産者名(法人格無)
    生産者名半角ｶﾅ
    生産者名欧字
    生産者住所自治省名
}

entity "馬主マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    馬主コード <<PK>>
    馬主名(法人格有)
    馬主名(法人格無)
    馬主名半角ｶﾅ
    馬主名欧字
    服色標示
}

entity "繁殖馬マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    繁殖登録番号 <<PK>>
    予備
    血統登録番号 <<FK>>
    予備
    馬名
    馬名半角ｶﾅ
    馬名欧字
    生年
    性別コード
    品種コード
    毛色コード
    繁殖馬持込区分
    輸入年
    産地名
    父馬繁殖登録番号 <<FK>>
    母馬繁殖登録番号 <<FK>>
}

entity "産駒マスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    血統登録番号 <<FK>>
    生年月日
    性別コード
    品種コード
    毛色コード
    産駒持込区分
    輸入年
    生産者コード
    産地名
    3代血統繁殖登録番号
}

entity "レコードマスタ" {
    レコード種別ID
    データ区分
    データ作成年月日
    レコード識別区分 <<PK>>
    開催年 <<PK>>
    開催月日 <<PK>>
    競馬場コード <<PK>>
    開催回[第N回] <<PK>>
    開催日目[N日目] <<PK>>
    レース番号 <<PK>>
    特別競走番号 <<PK>>
    競走名本題
    グレードコード
    競走種別コード <<PK>>
    距離 <<PK>>
    トラックコード <<PK>>
    レコード区分
    レコードタイム
    天候コード
    芝馬場状態コード
    ダート馬場状態コード
    レコード保持1_血統登録番号
    レコード保持1_調教師コード
    レコード保持1_騎手コード
    レコード保持1_負担重量
    レコード保持2_血統登録番号
    レコード保持2_調教師コード
    レコード保持2_騎手コード
    レコード保持2_負担重量
    レコード保持3_血統登録番号
    レコード保持3_調教師コード
    レコード保持3_騎手コード
    レコード保持3_負担重量
}

entity "坂路調教" {
レコード種別ID			
データ区分			
データ作成年月日			
トレセン区分			
調教年月日			
調教時刻			
血統登録番号			
			
<4ハロン800M>			
4ハロンタイム合計(800M～0M)			
ラップタイム(800M～600M)			
			
<3ハロン600M>			
3ハロンタイム合計(600M～0M)			
ラップタイム(600M～400M)			
			
<2ハロン400M>			
2ハロンタイム合計(400M～0M)			
ラップタイム(400M～200M)			
			
<1ハロン200M>			
ラップタイム(200M～0M)			
}


"特別登録馬" ||--|{ "特別登録馬_連番"
"特別登録馬" ||--|| "レース詳細"
"特別登録馬_連番" ||--|{ "馬毎レース情報"
"特別登録馬" ||--|| "払戻"
"特別登録馬_連番" }|--||"競走馬マスタ"
"馬毎レース情報" }|--||"競走馬マスタ"
"馬毎レース情報" }|--|{ "騎手マスタ"
"調教師マスタ" }|--|{ "特別登録馬_連番"
"調教師マスタ" }|--|{ "馬毎レース情報"
"調教師マスタ" }|--|{ "競走馬マスタ"
"調教師マスタ" }|--|{ "騎手マスタ"
"生産者マスタ" ||--|{ "競走馬マスタ"
"馬主マスタ" ||--|{ "競走馬マスタ"
"馬主マスタ" ||--|{ "馬毎レース情報"
"繁殖馬マスタ" }|--|{ "競走馬マスタ"
"繁殖馬マスタ" }|--|{ "繁殖馬マスタ"
"産駒馬マスタ" ||--|| "競走馬マスタ"
"産駒馬マスタ" }|--|| "生産者マスタ"
"産駒馬マスタ" ||--|{ "繁殖馬マスタ"
"レコードマスタ" }|--|{ "競走馬マスタ"

@enduml
